### ISSUE TITLE
Can't build with browserify

### ISSUE THREAD

**Issue by jwerle** [vicapow/react-map-gl-heatmap-overlay#2]
Since https://github.com/vicapow/webgl-heatmap/commit/54880b6c2edc0d6cfb2a9557bac85f189fe3a3b5, I've been unable to build this module.
Here is the output from my build step

```
 √ browserify -t babelify -t glslify app/main.js
SyntaxError: Unexpected token (1:10) while parsing file: /Users/jwerle/repos/littlstar/creators/node_modules/webgl-heatmap/vertex-shader-blit.glsl
    at Parser.pp.raise (/Users/jwerle/repos/littlstar/creators/node_modules/acorn/dist/acorn.js:1745:13)
    at Parser.pp.unexpected (/Users/jwerle/repos/littlstar/creators/node_modules/acorn/dist/acorn.js:2264:8)
    at Parser.pp.semicolon (/Users/jwerle/repos/littlstar/creators/node_modules/acorn/dist/acorn.js:2243:59)
    at Parser.pp.parseExpressionStatement (/Users/jwerle/repos/littlstar/creators/node_modules/acorn/dist/acorn.js:2677:8)
    at Parser.pp.parseStatement (/Users/jwerle/repos/littlstar/creators/node_modules/acorn/dist/acorn.js:2462:160)
    at Parser.pp.parseTopLevel (/Users/jwerle/repos/littlstar/creators/node_modules/acorn/dist/acorn.js:2379:21)
    at parse (/Users/jwerle/repos/littlstar/creators/node_modules/acorn/dist/acorn.js:101:12)
    at module.exports (/Users/jwerle/repos/littlstar/creators/node_modules/falafel/index.js:22:15)
    at /Users/jwerle/repos/littlstar/creators/node_modules/static-module/index.js:30:13
    at ConcatStream.<anonymous> (/Users/jwerle/repos/littlstar/creators/node_modules/static-module/node_modules/concat-stream/index.js:36:43)
```

**Comment by jwerle** [comment]
I noticed [this addition](https://github.com/stackgl/glslify#webpack-loader) to the glslify README and now wonder if by consequence webgl-heatmap is not compatible with browserify causing this module to fail a build. I could be missing a configuration setting or step.

**Comment by vicapow** [comment]
Hey @jwerle, I updated webgl-heatmap to 0.2.3. It uses only brfs instead of browserify-shader. can you give it a try and see if this fixes your issue? ref: https://github.com/vicapow/webgl-heatmap/commit/e731c7eb4e4ff42fa7178d3f811e5a34b0938ab4
